apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mainchart
  namespace: argo-cd
spec:
  destination:
    namespace: mainchart
    server: https://kubernetes.default.svc
  project: default
  source:
    path: svc/mainchart
    repoURL: 	https://github.com/samm-git/helmtest.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
